export const SEARCH_REPOS = "SEARCH_REPOS";
export const GET_REPO = "GET_REPO";
export const GET_MARKDOWN = "GET_MARKDOWN";
export const SEARCH_REPOSASC = "SEARCH_REPOSASC";
export const SEARCH_REPOSDESC = "SEARCH_REPOSDESC";
